apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: tech-explorer-ui
data:
  langgraph-api-url: "https://tech-explorer-agents-techx.apps.prod.rhoai.rh-aiservices-bu.com"
  api-base-url: "https://tech-explorer-agents-techx.apps.prod.rhoai.rh-aiservices-bu.com"
  # Add other configuration values as needed
