apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tech-explorer-ui-route
  labels:
    app: tech-explorer-ui
spec:
  to:
    kind: Service
    name: tech-explorer-ui-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
